matrix:
    include:
        -   os: linux
            dist: trusty
            sudo: required
            language: python
            python: 2.7
            before_install:
                - sudo apt-get update -qq
                - sudo apt-get install -qq libgsl0-dev libgmp-dev libmpfr-dev libsqlite0-dev
                - wget http://abacus.gene.ucl.ac.uk/software/indelible/EFBKqHdv0v7qir6CyeHgqaz/INDELibleV1.03.tar.gz
                - git clone https://github.com/adamallo/SimPhy simphy
                - tar -zxf INDELibleV1.03.tar.gz
                - pushd simphy && make && make clean && popd
                - pushd INDELibleV1.03/src && rm MersenneTwister.h &&  wget https://raw.githubusercontent.com/merlyescalona/indelible-ngsphy/master/src/MersenneTwister.h && g++ -o indelible -O4 indelible.cpp  && popd
                - export PATH=$PATH:$(pwd)/simphy/bin
                - export PATH=$PATH:$(pwd)/INDELibleV1.03/src
                - pip install -r requirements.txt
            install:
                - python setup.py install

script:
    - test/data.simulation.sh
